"""add warehouse_id to shipments

Revision ID: 60265f5dc3cb
Revises: feabe92d276b
Create Date: 2026-09-20 15:44:23.108859

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60265f5dc3cb'
down_revision: Union[str, None] = 'feabe92d276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shipments_warehouse_id'), 'shipments', ['warehouse_id'], unique=False)
    op.create_foreign_key(op.f('fk_shipments_warehouse_id_warehouses'), 'shipments', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shipments_warehouse_id_warehouses'), 'shipments', type_='foreignkey')
    op.drop_index(op.f('ix_shipments_warehouse_id'), table_name='shipments')
    op.drop_column('shipments', 'warehouse_id')
    # ### end Alembic commands ###