"""add alerts query indexes

Revision ID: 8a3965225cfe
Revises: ff27b49e4cc4
Create Date: 2026-09-20 10:06:44.226076

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3965225cfe'
down_revision: Union[str, None] = 'ff27b49e4cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_entity_type_entity_id', 'alerts', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_alerts_type_is_resolved', 'alerts', ['type', 'is_resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_type_is_resolved', table_name='alerts')
    op.drop_index('ix_alerts_entity_type_entity_id', table_name='alerts')
    # ### end Alembic commands ###