"""add warehouse_id to users

Revision ID: feabe92d276b
Revises: 1c4e8a6b9d02
Create Date: 2026-09-20 15:37:37.956510

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feabe92d276b'
down_revision: Union[str, None] = '1c4e8a6b9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_warehouse_id'), 'users', ['warehouse_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_warehouse_id_warehouses'), 'users', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_warehouse_id_warehouses'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_warehouse_id'), table_name='users')
    op.drop_column('users', 'warehouse_id')
    # ### end Alembic commands ###